const API_URL='https://ginseng-plus-api.onrender.com';
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('orderForm'),select=document.getElementById('package'),message=document.getElementById('formMessage'),summary=document.getElementById('orderSummary'),confirmation=document.getElementById('confirmation'),orderCard=document.querySelector('.order-summary-card');if(!form||!select||!message)return;
 const selected=new URLSearchParams(location.search).get('package');if(selected&&[...select.options].some(o=>o.value===selected))select.value=selected;
 let mobileSummary;
 if(orderCard){mobileSummary=document.createElement('button');mobileSummary.type='button';mobileSummary.className='mobile-order-summary';mobileSummary.setAttribute('aria-expanded','false');mobileSummary.innerHTML='<span><small>Your order</small><strong id="mobileSummaryPackage">Select a package</strong></span><b id="mobileSummaryPrice">—</b><i>View details ↓</i>';orderCard.before(mobileSummary);mobileSummary.addEventListener('click',()=>{const open=orderCard.classList.toggle('mobile-summary-open');mobileSummary.setAttribute('aria-expanded',String(open));mobileSummary.querySelector('i').textContent=open?'Hide details ↑':'View details ↓'})}
 const refresh=()=>{const value=select.value||'',amount=value.match(/—\s*(₦[\d,]+)/)?.[1]||'—',shortName=value?value.split(' — ')[0]:'Select a package';document.getElementById('checkoutPackageName').textContent=shortName;document.getElementById('checkoutPackagePrice').textContent=amount;document.getElementById('checkoutTotal').textContent=amount;document.getElementById('checkoutPackageBenefit').textContent=value.includes('3 Packs')?'Buy 3 Packs, Get 1 Pack Free':value.includes('2 Packs')?'Save ₦8,000 vs buying two starter packs':value?'Pay on delivery':'Your selected package will appear here.';const mobileName=document.getElementById('mobileSummaryPackage'),mobilePrice=document.getElementById('mobileSummaryPrice');if(mobileName)mobileName.textContent=shortName;if(mobilePrice)mobilePrice.textContent=amount};select.addEventListener('change',refresh);refresh();
 window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'checkout_viewed',package:select.value||'none'});
 form.addEventListener('submit',async event=>{event.preventDefault();message.textContent='Submitting your order...';message.className='form-status';const button=form.querySelector('button[type="submit"]');button.disabled=true;const data=Object.fromEntries(new FormData(form).entries());if(data.city==='__other__')data.city=String(data.other_city||'').trim();delete data.other_city;try{const response=await fetch(`${API_URL}/api/orders`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(data)});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload?.detail||`Server returned ${response.status}`);summary.innerHTML=`<div class="summary"><strong>Order ${escapeHtml(payload.id)}</strong><span>${escapeHtml(payload.package)}</span><span>Customer: ${escapeHtml(payload.name)}</span><span>Phone: ${escapeHtml(payload.phone)}</span><span>Delivery: ${escapeHtml(payload.city)}, ${escapeHtml(payload.state)}</span><span class="payment-line">Payment: <strong>PAY ON DELIVERY</strong></span></div>`;window.dataLayer.push({event:'order_submitted',package:payload.package||data.package});document.querySelector('.order-section')?.classList.add('hidden');confirmation?.classList.remove('hidden');confirmation?.scrollIntoView({behavior:'smooth'})}catch(error){message.textContent=`Order could not be submitted: ${error.message||'Please try again.'}`;message.className='form-status form-error'}finally{button.disabled=false}});
});