/* Nigerian state/city/town/LGA selector for checkout. */
(function(){
const CITIES_API_URL='https://countriesnow.space/api/v0.1/countries/state/cities',DATA_URL='https://cdn.jsdelivr.net/gh/Yerikmiller/Countries-States-Cities-JSON@latest/countries/NGA.json',CITY_DATA_URL='https://gist.githubusercontent.com/mr-chidex/3a51271217871827eb86fb664d29e7e5/raw/',LGA_DATA_URL='https://gist.githubusercontent.com/judeebene/2b3f9c0c816b68ff5dd5fa40c48a3d5c/raw/22e0b687f267d55e28e6428ce360118142b6f1fe/state%20and%20lga%20json%20in%20nigeria',CACHE_KEY='ginsengPlusNigeriaLocations:v6';
const stateSelect=document.getElementById('state'),citySelect=document.getElementById('city'),otherCityWrap=document.getElementById('otherCityWrap'),otherCity=document.getElementById('otherCity');if(!stateSelect||!citySelect)return;let fallbackPromise,cityPromise,lgaPromise;const memory=new Map();
const key=v=>String(v||'').trim().toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');const match=(a,b)=>{a=key(a);b=key(b);if(a===b)return true;const fct=new Set(['federalcapitalterritoryfct','federalcapitalterritory','abujafederalcapitalterritory','abujafct','fct','fctfederalcapitalterritory']);return fct.has(a)&&fct.has(b)};const clean=items=>[...new Set((Array.isArray(items)?items:[]).map(x=>typeof x==='string'?x:x?.name||x?.city||x?.town||'').map(x=>String(x).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
async function json(url,label,options){const r=await fetch(url,options||{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${label}: ${r.status}`);return r.json()}
function cached(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch{return null}}function cache(data){try{localStorage.setItem(CACHE_KEY,JSON.stringify(data))}catch{}}
async function fallback(){if(!fallbackPromise){const c=cached();fallbackPromise=c?Promise.resolve(c):json(DATA_URL,'Fallback locations').then(d=>(cache(d),d))}return fallbackPromise}async function cityData(){return cityPromise||(cityPromise=json(CITY_DATA_URL,'City data'))}async function lgaData(){return lgaPromise||(lgaPromise=json(LGA_DATA_URL,'LGA data'))}
async function apiCities(state){const p=await json(CITIES_API_URL,'Cities API',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({country:'Nigeria',state})});return clean(p.data)}async function fallbackCities(state){const d=await fallback(),states=Array.isArray(d)?d:d.states||d.state||[],s=states.find(x=>match(x?.name||x?.state||x?.title,state));return clean(s?.cities||s?.city||s?.towns||s?.town)}async function datasetCities(state){const d=await cityData(),states=Array.isArray(d)?d:d?.states||[],s=states.find(x=>match(x?.state?.name||x?.name||x?.state,state));return clean(s?.state?.cities||s?.cities||s?.city)}async function lgas(state){const d=await lgaData(),states=Array.isArray(d)?d:d?.states||[],s=states.find(x=>match(x?.name||x?.state,state));return clean(s?.locals)}
function manual(show){otherCityWrap?.classList.toggle('is-hidden',!show);if(otherCity){otherCity.required=show;if(!show)otherCity.value=''}}function render(cities){citySelect.innerHTML='<option value="">Select your city / town / LGA</option>';cities.forEach(city=>citySelect.add(new Option(city,city)));citySelect.add(new Option('My city / town is not listed','__other__'));citySelect.disabled=false;manual(false)}function manualOnly(){citySelect.innerHTML='';citySelect.add(new Option('Enter my city / town manually','__other__'));citySelect.value='__other__';citySelect.disabled=false;manual(true)}
async function populate(state){citySelect.disabled=true;citySelect.innerHTML='<option>Loading cities / towns…</option>';manual(false);if(!state){citySelect.innerHTML='<option value="">Select your state first</option>';return}const k=key(state);if(memory.has(k))return render(memory.get(k));const results=await Promise.allSettled([apiCities(state),fallbackCities(state),datasetCities(state),lgas(state)]),cities=clean(results.flatMap(r=>r.status==='fulfilled'?r.value:[]));if(!cities.length)return manualOnly();memory.set(k,cities);render(cities)}
stateSelect.addEventListener('change',()=>populate(stateSelect.value));citySelect.addEventListener('change',()=>manual(citySelect.value==='__other__'));
})();