function checkoutUrl(packageName){return `checkout.html?package=${encodeURIComponent(packageName)}`}
function track(eventName,details={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:eventName,...details})}
document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.package[data-package]').forEach(button=>button.addEventListener('click',()=>{const packageName=button.dataset.package||'';track('package_selected',{package:packageName});window.location.href=checkoutUrl(packageName)}));
  document.getElementById('claimOffer')?.addEventListener('click',()=>{const packageName='3 Packs + 1 Free — ₦59,900';track('special_offer_selected',{package:packageName});window.location.href=checkoutUrl(packageName)});
  document.querySelectorAll('[data-track]').forEach(element=>element.addEventListener('click',()=>track('cta_clicked',{cta:element.dataset.track})));
  const bar=document.getElementById('mobilePurchaseBar'),packages=document.getElementById('packages');
  if(bar&&packages&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{bar.classList.toggle('is-hidden',entries[0].isIntersecting)},{threshold:.08});observer.observe(packages)}

  const nav=document.querySelector('.nav'),desktopNav=document.querySelector('.desktop-nav');
  if(nav&&desktopNav){const toggle=document.createElement('button');toggle.type='button';toggle.className='mobile-menu-toggle';toggle.setAttribute('aria-label','Open navigation');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span></span><span></span><span></span>';const panel=document.createElement('div');panel.className='mobile-nav-panel';panel.innerHTML=desktopNav.innerHTML;nav.insertBefore(toggle,nav.querySelector('.nav-cta'));nav.after(panel);const close=()=>{panel.classList.remove('is-open');toggle.classList.remove('is-open');toggle.setAttribute('aria-expanded','false')};toggle.addEventListener('click',()=>{const open=panel.classList.toggle('is-open');toggle.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open))});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));document.addEventListener('click',e=>{if(!panel.contains(e.target)&&!toggle.contains(e.target))close()})}

  const reviewGrid=document.querySelector('.reviews-grid'),reviews=reviewGrid?[...reviewGrid.querySelectorAll('.customer-review')]:[];
  if(reviewGrid&&reviews.length>1){const nav=document.createElement('div');nav.className='review-carousel-nav';nav.setAttribute('aria-label','Customer review navigation');reviews.forEach((_,i)=>{const dot=document.createElement('button');dot.type='button';dot.setAttribute('aria-label',`Show review ${i+1}`);dot.addEventListener('click',()=>reviews[i].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}));nav.appendChild(dot)});reviewGrid.after(nav);const dots=[...nav.children];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;const index=reviews.indexOf(visible.target);dots.forEach((d,i)=>d.classList.toggle('is-active',i===index))},{root:reviewGrid,threshold:[.55,.75]});reviews.forEach(r=>observer.observe(r));dots[0]?.classList.add('is-active')}
});